# Generated by Django 2.0.1 on 2018-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
