# Generated by Django 2.0.1 on 2018-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_competency_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='id',
        ),
        migrations.AlterField(
            model_name='competency',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
